version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: ses-nginx
    restart: always
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html/pika-admin
    networks:
      - ses-net
    ports:
      - 8080:9090

networks:
  ses-net:
    external:
      name: docker-compose_sc-net
