version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: pika-nginx
    restart: always
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./dist:/usr/share/nginx/html/pika-admin
    networks:
      - pika-net
    ports:
      - 8080:9090
